// <auto-generated />
using System;
using JeBalance.Infrastructure.SQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JeBalance.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240127153952_t0")]
    partial class t0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JeBalance.Infrastructure.SQLServer.Model.DenonciationSQLS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Delit")
                        .HasColumnType("int")
                        .HasColumnName("delit");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("datetime2")
                        .HasColumnName("horodatage");

                    b.Property<string>("Informateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informateur");

                    b.Property<string>("PaysEvasion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paysEvasion");

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reponse");

                    b.Property<int>("StatutInfo")
                        .HasColumnType("int")
                        .HasColumnName("statutInfo");

                    b.Property<int>("StatutSuspect")
                        .HasColumnType("int")
                        .HasColumnName("statutSuspect");

                    b.Property<string>("Suspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("suspect");

                    b.HasKey("Id");

                    b.ToTable("DENONCIATIONS", "app");
                });

            modelBuilder.Entity("JeBalance.Infrastructure.SQLServer.Model.PersonneSQLS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom");

                    b.Property<int>("Statut")
                        .HasColumnType("int")
                        .HasColumnName("statut");

                    b.HasKey("Id");

                    b.ToTable("PERSONNES", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
